export const REQUEST_GET_ALL_USER = 'REQUEST_GET_ALL_USER';
export const SUCCESS_GET_ALL_USER='SUCCESS_GET_ALL_USER';

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const SUCCESS_ADD_USER = 'SUCCESS_ADD_USER';

export const REQUEST_ERROR = 'REQUEST_ERROR';

export const REQUEST_ADD_TOKEN = 'REQUEST_ADD_TOKEN';
